# Generated by Django 5.0.1 on 2024-01-30 23:26

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='Name')),
                ('descriptions', models.CharField(db_index=True, max_length=750, verbose_name='Description')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Images')),
                ('place_type', models.CharField(choices=[('Private and Luxury', 'Private and Luxury'), ('Full day Tours', 'Full day tours'), ('Day trips', 'Day Trips'), ('Forest', 'Forest'), ('Favourites', 'Favourites')], max_length=50, verbose_name='Place Type')),
                ('time_to_travel', models.CharField(max_length=10, verbose_name='Time To Travel')),
                ('google_map_link', models.CharField(max_length=500, verbose_name='Google Map')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'db_table': 'place',
            },
        ),
    ]
